POST http://localhost:3002/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
POST http://localhost:3002/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}


###
GET http://localhost:3002/user/tweets/feed/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
GET http://localhost:3002/user/following/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
GET http://localhost:3002/user/followers/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
GET http://localhost:3002/tweets/1/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
GET http://localhost:3002/tweets/1/likes/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
GET http://localhost:3002/tweets/2/replies/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
GET http://localhost:3002/user/tweets/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
POST http://localhost:3002/user/tweets/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 

###
 
DELETE http://localhost:3002/tweets/1/
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjk3MjA1ODg4fQ.uNurSPjMjqWekSQAyrqCThIXjjlXJaZD8_iKOj8WMms 
